conversation_flow_designing_task:
  description: >
    Create pywce YAML templates that defines the chatbot's conversation flow based on the user's requirements.
    Ensure the flow is intuitive
    Covers all edge cases
    And aligns with the chatbot's purpose.
  expected_output: >
    A complete pywce YAML template file that includes:
    Engine supported message types (e.g. text, button, list e.t.c).
    Routes for user responses.
    Hooks for custom logic.
  agent: conversation_flow_designer
  output_file: chatbot.yaml

developer_task:
  description: >
    Analyze the user requirements you got and the template hooks defined.
    Write python hooks code to handle custom logic for the chatbot
    Such as processing user input, saving session data and integrating with other services or with external APIs
    Make sure the code uses best python practises with appropriate code documentation
    The chatbot YAML template is found in the chatbot.yaml file
  expected_output: >
    Python functions for hooks 
    Define required engine hooks where necessary that integrate seamlessly with the defined YAML templates.
    Product working, clean and testable python functions
  agent: hook_developer
  output_file: hooks.py

reviewer_task:
  description: >
    Ensure to validate the pywce engine YAML templates saved in chatbot.yaml
    Validate template python hooks saved in hooks.py file to ensure they are syntactically correct
    Ensure generated python code adhere to best practises
  expected_output: >
    A report detailing all issues found.
    Provide suggestions for improvement
    The reviewed python function hooks should be error-free and optimized
  agent: code_reviewer
  output_file: issues.md

reporter_task:
  description: >
    Create documentation that explains the chatbot's conversation flow, hooks and usage instructions
    Ensure the documentation is clear and output in markdown format
    Review the generated engine YAML template, chatbot.yaml and generated engine defined python template hooks in hooks.py
  expected_output: >
    A markdown file that includes
    - overview of the chatbot's functionality
    - Explanation of the conversation flow
    - Usage instructions for hooks
  agent: code_reporter
  output_file: chatbot.md
